version: "3"
services:
  app:
    # image: "${IMAGE:-ett-de:dev}"
    build: .
    ports:
      - 8080:8080
    environment:
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/ett_de_production
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - ENV=production
      - HANAMI_ENV=production
      - PGPASSWORD=postgres
    links:
      - postgres
      - rabbitmq
      - redis
  worker:
    # image: "${IMAGE:-ett-de:dev}"
    build: .
    command: 'worker'
    environment:
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/ett_de_production
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - ENV=development
      - HANAMI_ENV=development
      - PGPASSWORD=postgres
    links:
      - postgres
      - rabbitmq
      - redis

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis
