version: "3"
networks:
  local:
  proxy-tier:
    external: true

services:
  app:
    # image: "${IMAGE:-ett-de:dev}"
    build: .
    ports:
      - 8080:8080
    environment:
      - VIRTUAL_HOST=ett.vlt81.de
      - LETSENCRYPT=ett.vlt81.de
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/ett_de_production
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - ENV=production
      - HANAMI_ENV=production
      - PGPASSWORD=postgres
    networks:
      - local
      - proxy-tier
  worker:
    # image: "${IMAGE:-ett-de:dev}"
    build: .
    command: 'worker'
    environment:
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/ett_de_production
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - ENV=development
      - HANAMI_ENV=development
      - PGPASSWORD=postgres
    networks:
      - local

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - local
  redis:
    image: redis
    networks:
      - local
